// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://loypvbhwcqmzamxzwoic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxveXB2Ymh3Y3FtemFteHp3b2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE5OTIsImV4cCI6MjA3MTk3Nzk5Mn0.zQzZFTEPjXbbNHvaty1M_zWcKatbBEKHqeq9l0lTF7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});